#!/usr/bin/env bash
set -euo pipefail

usage() {
	echo "usage: $0 RELEASE-TAG DIST OUTPUT" >&2
}

release_tag="${1:-}"
dist_dir="${2:-}"
output="${3:-}"
if [[ -z "${release_tag}" || -z "${dist_dir}" || -z "${output}" ]]; then
	usage
	exit 2
fi
if [[ "${release_tag}" != v* ]]; then
	echo "release tag must start with v: ${release_tag}" >&2
	exit 2
fi
if [[ ! -f "${dist_dir}/checksums.txt" ]]; then
	echo "missing checksums.txt in ${dist_dir}" >&2
	exit 1
fi

version="${release_tag#v}"
checksum_for() {
	local filename="$1"
	local checksum
	checksum="$(awk -v target="${filename}" '$2 == target { print $1; exit }' "${dist_dir}/checksums.txt")"
	if [[ ! "${checksum}" =~ ^[[:xdigit:]]{64}$ ]]; then
		echo "missing or invalid SHA-256 for ${filename}" >&2
		exit 1
	fi
	printf '%s\n' "${checksum}"
}

darwin_amd64="SpeeDNS_${version}_darwin_amd64.tar.gz"
darwin_arm64="SpeeDNS_${version}_darwin_arm64.tar.gz"
linux_amd64="SpeeDNS_${version}_linux_amd64.tar.gz"
linux_arm64="SpeeDNS_${version}_linux_arm64.tar.gz"

sha_darwin_amd64="$(checksum_for "${darwin_amd64}")"
sha_darwin_arm64="$(checksum_for "${darwin_arm64}")"
sha_linux_amd64="$(checksum_for "${linux_amd64}")"
sha_linux_arm64="$(checksum_for "${linux_arm64}")"

mkdir -p "$(dirname "${output}")"
{
	printf '%s\n' '# This file is generated by the SpeeDNS release workflow. Do not edit.'
	printf 'cask "speedns" do\n'
	printf '  version "%s"\n\n' "${version}"
	printf '  on_macos do\n'
	printf '    on_intel do\n'
	printf '      sha256 "%s"\n' "${sha_darwin_amd64}"
	printf '      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_darwin_amd64.tar.gz",\n'
	printf '%s\n' '        verified: "github.com/crypt0rr/SpeeDNS/releases/download"'
	printf '    end\n'
	printf '    on_arm do\n'
	printf '      sha256 "%s"\n' "${sha_darwin_arm64}"
	printf '      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_darwin_arm64.tar.gz",\n'
	printf '%s\n' '        verified: "github.com/crypt0rr/SpeeDNS/releases/download"'
	printf '    end\n'
	printf '  end\n\n'
	printf '  on_linux do\n'
	printf '    on_intel do\n'
	printf '      sha256 "%s"\n' "${sha_linux_amd64}"
	printf '      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_linux_amd64.tar.gz",\n'
	printf '%s\n' '        verified: "github.com/crypt0rr/SpeeDNS/releases/download"'
	printf '    end\n'
	printf '    on_arm do\n'
	printf '      sha256 "%s"\n' "${sha_linux_arm64}"
	printf '      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_linux_arm64.tar.gz",\n'
	printf '%s\n' '        verified: "github.com/crypt0rr/SpeeDNS/releases/download"'
	printf '    end\n'
	printf '  end\n\n'
	printf '%s\n' '  name "speedns"'
	printf '%s\n' '  desc "Cross-platform DNS transport speed test CLI"'
	printf '%s\n' '  homepage "https://github.com/crypt0rr/SpeeDNS"'
	printf '%s\n' ''
	printf '%s\n' '  livecheck do'
	printf '%s\n' '    skip "Auto-generated on release."'
	printf '%s\n' '  end'
	printf '%s\n' ''
	printf '%s\n' '  binary "speedns"'
	printf '%s\n' ''
	printf '%s\n' 'end'
} >"${output}"

echo "generated Homebrew cask: ${output}"
